# Generated by Django 2.1 on 2018-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(verbose_name='quantité par personne en grammes'),
        ),
    ]
