# Generated by Django 2.1 on 2018-08-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20180829_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='secable',
            field=models.BooleanField(default=True, verbose_name='sécable'),
        ),
    ]
