# Generated by Django 2.1 on 2018-08-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meal_nb_of_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'repas', 'verbose_name_plural': 'repas'},
        ),
    ]
