# Generated by Django 2.1 on 2018-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20180829_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='status',
            field=models.IntegerField(choices=[(0, 'en attente'), (1, 'prévu dans une liste'), (2, 'acheté')], default=0),
        ),
    ]
