# Generated by Django 2.1 on 2018-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20180830_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='foods',
            field=models.ManyToManyField(related_name='suppliers', to='meals.Food'),
        ),
    ]
