# Generated by Django 2.1 on 2018-08-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_auto_20180830_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provision',
            options={'verbose_name': 'aliment pour un repas', 'verbose_name_plural': 'aliments pour un repas'},
        ),
        migrations.RemoveField(
            model_name='listelement',
            name='provision',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='provisions',
        ),
        migrations.AddField(
            model_name='listelement',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meals.Food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='foods',
            field=models.ManyToManyField(through='meals.ListElement', to='meals.Food'),
        ),
        migrations.AlterField(
            model_name='listelement',
            name='status',
            field=models.IntegerField(choices=[(1, 'prévu'), (2, 'acheté'), (3, 'supprimé')], default=1, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(verbose_name='date du repas'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='moment',
            field=models.IntegerField(choices=[(0, 'midi'), (1, 'soir')], verbose_name='midi ou soir'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='nb_of_guests',
            field=models.IntegerField(verbose_name='nombre de convives'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='quantity',
            field=models.IntegerField(verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='status',
            field=models.IntegerField(choices=[(0, 'en attente'), (1, 'prévu dans une liste'), (2, 'acheté')], default=0, verbose_name='état'),
        ),
    ]
